service: beer-rating

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:*:*:table/slsbeer"
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: beer/hello
          method: get
  addRating:
    handler: handler.addRating
    events:
      - http:
          path: beer/rating
          method: post
  getRating:
    handler: handler.getRating
    events:
      - http:
          path: beer/rating/{beer}
          method: get
  allRatings:
    handler: handler.allRatings
    events:
      - http:
          path: beer/ratings
          method: get
resources:
  Resources:
    BeerDynamo:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: slsbeer
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
